### ISSUE TITLE
README 오타

### ISSUE THREAD

**Issue by zych1751** [kakao/kakao_flutter_sdk#61]
pubspec.yaml 에 적혀있는 정보와 README.md 에 적혀있는 정보가 다릅니다.
json_annotation 에 json_serializable 링크가 걸려있고, 버전도 3.3.0으로 다르게 적혀있습니다.
확인 부탁드리겠습니다.

```yaml
# pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  # flutter_web_plugins:
  #   sdk: flutter
  json_annotation: ^3.0.0
  ...
```

```
# README.md

### dependencies

Kakao Flutter SDK has following dependencies:

1. [json_annotation](https://pub.dev/packages/json_serializable) (3.3.0)
...
```
